---
- name: Install java
  hosts: localhost
  connection: local
  roles:
    - role: homebrew
      vars:
        homebrew_taps: []
        homebrew_cask_packages:
          - { name: corretto }
        homebrew_packages: []
