---
- name: Install kubernetes products
  hosts: localhost
  connection: local
  roles:
    - role: homebrew
      vars:
        homebrew_taps:
          - { tap: homebrew/cask-versions }
        homebrew_cask_packages: []
        homebrew_packages:
          - { name: kubernetes-helm }
          - { name: skaffold }
          - { name: stern }
