---
- name: Install utility tools
  hosts: localhost
  connection: local
  roles:
    - role: homebrew
      vars:
        homebrew_taps:
          - { tap: homebrew/cask-versions }
          - { tap: heroku/brew }
          - { tap: k1LoW/tap }
        homebrew_cask_packages: []
        homebrew_packages:
          - { name: ffmpeg }
          - { name: ghostscript }
          - { name: graphviz }
          - { name: heroku/brew/heroku }
          - { name: httpie }
          - { name: hub }
          - { name: imagemagick }
          - { name: jo }
          - { name: jq }
          - { name: k1LoW/tap/colr }
          - { name: k1LoW/tap/evry }
          - { name: k1LoW/tap/filt }
          - { name: k1LoW/tap/harvest }
          - { name: k1LoW/tap/tbls }
          - { name: tig }
          - { name: tmux }
          - { name: tree }
          - { name: upx }
