---
lang_go_packages:
  - { name: gocode, path: github.com/nsf/gocode }
  - { name: godoc, path: golang.org/x/tools/cmd/godoc }
  - { name: goimports, path: golang.org/x/tools/cmd/goimports }
  - { name: golint, path: github.com/golang/lint/golint }
  - { name: gore, path: github.com/motemen/gore }
  - { name: gox, path: github.com/mitchellh/gox }
  - { name: pp, path: github.com/k0kubun/pp }
  - { name: qq, path: github.com/mattn/qq/... }
  - { name: stringer, path: go get golang.org/x/tools/cmd/stringer }

lang_pip_packages:
  - { name: awscli }
  - { name: aws-vapor }
  - { name: Sphinx }

lang_pip3_packages:
  - { name: acdcli }
  - { name: bokeh }
  - { name: jupyter }
  - { name: matplotlib }
  - { name: nose }
  - { name: numpy }
  - { name: pandas }
  - { name: scipy }
  - { name: scikit-image }
  - { name: scikit-learn }
  - { name: seaborn }
  - { name: tox }

lang_ruby_version: 2.3.3

lang_gem_packages:
  - { name: bundler }
  - { name: rake }
