---
- name: Clone git repository
  git:
    repo: "{{ poetry_remote_repo }}"
    dest: "{{ poetry_local_repo }}"
    accept_hostkey: yes

- name: Check poetry exists
  command: "{{ poetry_check_poetry }}"
  register: res
  check_mode: no
  failed_when: no
  changed_when: res.rc != 0

- name: Run installer
  shell:
    cmd: python3 "{{ poetry_local_repo }}/get-poetry.py"
  when: res is changed

- name: Generate poetry completion
  shell:
    cmd: "{{ poetry_poetry_exe }} completions zsh >{{ poetry_poetry_completion }}"
  when: res is changed
