---
- name: Install python packages via pip
  pip:
    name: "{{ item.name }}"
    state: "{{ item.state | default('latest') }}"
  with_items:
    - "{{ lang_pip_packages }}"
  notify:
    - Rehash pyenv
