---
- name: Change Ruby version
  shell: |
    bash -cl 'rbenv global "{{ lang_ruby_version }}"'

- name: Change Java version
  shell: |
    source ~/.sdkman/bin/sdkman-init.sh && sdk default java "{{ lang_java_version }}"
  args:
    executable: /bin/bash

- name: Change Groovy version
  shell: |
    source ~/.sdkman/bin/sdkman-init.sh && sdk default groovy "{{ lang_groovy_version }}"
  args:
    executable: /bin/bash

- name: Change Scala version
  shell: |
    source ~/.sdkman/bin/sdkman-init.sh && sdk default scala "{{ lang_scala_version }}"
  args:
    executable: /bin/bash

- name: Change Kotlin version
  shell: |
    source ~/.sdkman/bin/sdkman-init.sh && sdk default kotlin "{{ lang_kotlin_version }}"
  args:
    executable: /bin/bash

- name: Change Gradle version
  shell: |
    source ~/.sdkman/bin/sdkman-init.sh && sdk default gradle "{{ lang_gradle_version }}"
  args:
    executable: /bin/bash

- name: Change sbt version
  shell: |
    source ~/.sdkman/bin/sdkman-init.sh && sdk default sbt "{{ lang_sbt_version }}"
  args:
    executable: /bin/bash
