---
- name: Clone git repositories
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    accept_hostkey: yes
  with_items:
    - "{{ env_git_repositories }}"

- name: Run dotfiles setup
  shell: bash setup.sh
  args:
    chdir: "{{ env_ghq_root }}/ohtomi/dotfiles"

- name: Create pkg directory
  file:
    path: ~/pkg
    state: directory

- name: Download pkg files
  get_url:
    url: "{{ item.url }}"
    dest: "~/pkg/{{ item.file }}"
  with_items:
    - "{{ env_pkg_urls }}"

- name: Run pkg installer
  shell: sudo installer -package ~/pkg/{{ item.file }} -target /
  with_items:
    - "{{ env_pkg_urls }}"

- name: Create workbench directory for kindlizer
  file:
    path: ~/workbench/kindlizer
    state: directory

- name: Add /usr/local/bin/bash to /etc/shells
  lineinfile:
    dest: /etc/shells
    line: /usr/local/bin/bash
  become: yes

- name: Change shell
  shell: chsh -s /usr/local/bin/bash
