---
- name: Clone git repositories
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    accept_hostkey: yes
  with_items:
    - "{{ env_git_repositories }}"

- name: Run dotfiles setup
  shell: bash setup.sh
  args:
    chdir: "{{ env_ghq_root }}/ohtomi/dotfiles"
