---
- name: Clone git repositories
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    accept_hostkey: yes
  with_items:
    - "{{ env_git_repositories }}"

- name: Run dotfiles setup
  shell: bash setup.sh
  args:
    chdir: "{{ env_ghq_root }}/ohtomi/dotfiles"

- name: Add "{{ env_shell }}" to /etc/shells
  lineinfile:
    dest: /etc/shells
    line: "{{env_shell }}"
  become: yes

- name: Check if current shell is "{{ env_shell }}"
  shell: bash -cl 'echo $SHELL' | grep -F "{{ env_shell }}"
  register: res
  check_mode: no
  failed_when: no
  changed_when: res.rc != 0
  notify:
    - Change shell

- name: Flush handlers
  meta: flush_handlers
